# Site settings
title:              the CV template
author:             your name
email:              you email
description:        desc
keywords:           [kw1, kw2, kw3]
url:                http://mageluer.coding.me/CV

# Jekyll
markdown:           kramdown
highlighter:        rouge
kramdown:
  auto_ids:         true
  footnote_nr:      1
  entity_output:    as_char
  toc_levels:       1..6
  enable_coderay:   false
mathjax:            true

########################################################################
# Begin CV Edit
########################################################################

# Personal Info
info:
  avatar:          images/fucku.png
  name:            Zilu Tang
  address:         Wuhan University, Wuhan, China
  email:           tangzilu@whu.edu.cn
  tel:             +86-15207175816
  web:             www.maybemad.github.io
  pdf:             upload/cv.pdf


# Education
education:
  - period:        Sep 2014 - present
    institute:     Wuhan University
    school:        College of Chemistry and Molecular Sciences
  

# Skills
skills:
  ih:   
    -               300 MHz NMR spectrometer       
    -               HPLC, GC, and GC-MS     
  da: 
    -               Experience of interpreting 1H, 13C, HMQC NMR spectroscopy
    -               Experience of interpreting GC and GC-MS spectroscopy


# TOEFL & GRE
stdtest:
  display:         true
  toefl:           81
  gre:             310

# Experience
experience:
  - period:        Oct 2014 - present
    institute:     Green Catalysis Institution (College of Chemistry and Molecular Sciences, Wuhan University)
    desc:          Prof. Aiwen Lei
    project:
      -            Transition-metal-catalyzed oxidative coupling reactions  
      -            Visible-light mediated photocatalysis  
      

  

# Publications
publication:
  - time:          2017-05-24
    title:         H. Yi.; H. Chen.; C.-L. Bian.; <b>Z.-L. Tang.</b>; A. Singh.; X.-T. Qi.; X.-Y. Yue.; Y. Lan.; J.-F. Lee.; and A.-W. Lei.; <i>Chem. Commun.</i> <b>2017</b>,53, 6736-6739. 
  - time:          2017-07-13
    title:         H. Yi.; <b>Z.-L. Tang.</b>; C.-L. Bian.; H. Chen.; X.-T. Qi.; X.-Y. Yue.; Y. Lan.; J.-F. Lee.; and A.-W. Lei.;<i>Chem. Commun.</i>, <b>2017</b>,53, 8984-8987
  


# Activities
activity:
  display:        true
  hobby:          [hiking, table tennis, Dota2]
  experience:
    -             Travelling footprints left over 20 cities
    
  

